version: '3'

services:
  redis:
    image: redis:latest

  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  database_test:  # Nuevo servicio para la base de datos de prueba
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB:-test_database}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${TEST_POSTGRES_USER:-app}
    volumes:
      - database_test_data:/var/lib/postgresql/data:rw
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  database_test_data:
